version: '3.8'

services:

  mssql:
    build: ./Databases/SqlServer
    restart: always
    ports:
      - 1433:1433

  mongo:
    build: ./Databases/MongoDb
    restart: always
    ports:
      - 27017:27017
