services:

  mssql:
    container_name: mssql
    build: ./docker-images/SqlServer
    restart: always
    networks:
      - database
    ports:
      - 1433:1433

  mongodb:
    container_name: mongodb
    build: ./docker-images/MongoDb
    restart: always
    networks:
      - nosql
    ports:
      - 27017:27017

  rabbitmq:
    container_name: rabbitmq
    build: ./docker-images/RabbitMq
    restart: always
    networks:
      - message-broker
    ports:
      - 5672:5672
      - 15672:15672

  authentication-api:
    container_name: authentication-api
    image: ${DOCKER_REGISTRY-}authentication-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - application
      - database
    ports:
      - "7234:7234"
    build:
      context: ./Projects/Authentication
      dockerfile: ./Dockerfile
    depends_on:
      - mssql

  catalog-api:
    container_name: catalog-api
    image: ${DOCKER_REGISTRY-}catalog-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - application
      - database
      - nosql
    ports:
      - "7274:7274"
    build:
      context: .
      dockerfile: Projects/Catalogs/Dockerfile
    depends_on:
      - mssql
      - mongodb

  cart-api:
    container_name: cart-api
    image: ${DOCKER_REGISTRY-}cart-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - application
      - nosql
    ports:
      - "7292:7292"
    build:
      context: .
      dockerfile: Projects/Carts/Dockerfile
    depends_on:
      - mongodb

  payment-worker:
    container_name: payment-worker
    image: ${DOCKER_REGISTRY-}payment-worker
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - database
      - message-broker
    build:
      context: .
      dockerfile: Projects/Payments/Dockerfile
    depends_on:
      - mssql
      - rabbitmq

networks:
  database:
    name: database
    driver: bridge
  nosql:
    name: nosql
    driver: bridge
  message-broker:
    name: message-broker
    driver: bridge
  application:
    name: application
    driver: bridge