services:

  mssql:
    build: ./Databases/SqlServer
    restart: always
    ports:
      - 1433:1433

  mongodb:
    build: ./Databases/MongoDb
    restart: always
    ports:
      - 27017:27017

  rabbitmq:
    build: ./BrokersMessage/RabbitMq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:5000"
    build:
      context: .
      dockerfile: Projects/Catalogs/Dockerfile
    depends_on:
      - mssql
      - mongodb