// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace EM.Authentication.BehaviorTests.Features.Users
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UserManagementFeature : object, global::Xunit.IClassFixture<UserManagementFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Users", "User management", "In order to manage platform users\r\nAs an authorized user\r\nI want to create and ma" +
                "intain user accounts", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UserManagement.feature"
#line hidden
        
        public UserManagementFeature(UserManagementFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Users/UserManagement.feature.ndjson", 25);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Register a new user successfully")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Register a new user successfully")]
        [global::Xunit.TraitAttribute("Category", "UserRegistration")]
        public async global::System.Threading.Tasks.Task RegisterANewUserSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "UserRegistration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register a new user successfully", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
 await testRunner.AndAsync("I have user registration data with \"valid values\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
 await testRunner.WhenAsync("I register the user", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
 await testRunner.ThenAsync("the new user must be registered", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Register a user with an unauthorized profile")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Register a user with an unauthorized profile")]
        [global::Xunit.TraitAttribute("Category", "UserRegistration")]
        public async global::System.Threading.Tasks.Task RegisterAUserWithAnUnauthorizedProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "UserRegistration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register a user with an unauthorized profile", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
 await testRunner.GivenAsync("I am authenticated in with the \"customer profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
 await testRunner.AndAsync("I have user registration data with \"valid values\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.WhenAsync("I register the user", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
 await testRunner.ThenAsync("the user registration must be rejected due to insufficient permissions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Register a user without being authenticated")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Register a user without being authenticated")]
        [global::Xunit.TraitAttribute("Category", "UserRegistration")]
        public async global::System.Threading.Tasks.Task RegisterAUserWithoutBeingAuthenticated()
        {
            string[] tagsOfScenario = new string[] {
                    "UserRegistration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register a user without being authenticated", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
 await testRunner.GivenAsync("I am not authenticated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 24
 await testRunner.AndAsync("I have user registration data with \"valid values\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
 await testRunner.WhenAsync("I register the user", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
 await testRunner.ThenAsync("the user registration must be rejected because the user is not authenticated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Register a user with invalid authenticated")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Register a user with invalid authenticated")]
        [global::Xunit.TraitAttribute("Category", "UserRegistration")]
        public async global::System.Threading.Tasks.Task RegisterAUserWithInvalidAuthenticated()
        {
            string[] tagsOfScenario = new string[] {
                    "UserRegistration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register a user with invalid authenticated", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
 await testRunner.GivenAsync("I am not authenticated due to invalid credentials", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
 await testRunner.AndAsync("I have user registration data with \"valid values\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
 await testRunner.WhenAsync("I register the user", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
 await testRunner.ThenAsync("the user registration must be rejected because the user is not authenticated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Register user with default values")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Register user with default values")]
        [global::Xunit.TraitAttribute("Category", "UserRegistration")]
        public async global::System.Threading.Tasks.Task RegisterUserWithDefaultValues()
        {
            string[] tagsOfScenario = new string[] {
                    "UserRegistration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register user with default values", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
 await testRunner.AndAsync("I have user registration data with \"default values\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.WhenAsync("I register the user", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table6.AddRow(new string[] {
                            "The username cannot be null or empty"});
                table6.AddRow(new string[] {
                            "The email address cannot be null or empty"});
                table6.AddRow(new string[] {
                            "The password cannot be null or empty"});
#line 40
 await testRunner.ThenAsync("the user registration must be rejected due to validation errors", ((string)(null)), table6, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Register user with null values")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Register user with null values")]
        [global::Xunit.TraitAttribute("Category", "UserRegistration")]
        public async global::System.Threading.Tasks.Task RegisterUserWithNullValues()
        {
            string[] tagsOfScenario = new string[] {
                    "UserRegistration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register user with null values", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 49
 await testRunner.AndAsync("I have user registration data with \"null values\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
 await testRunner.WhenAsync("I register the user", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table7.AddRow(new string[] {
                            "The username cannot be null or empty"});
                table7.AddRow(new string[] {
                            "The email address cannot be null or empty"});
                table7.AddRow(new string[] {
                            "The password cannot be null or empty"});
#line 51
 await testRunner.ThenAsync("the user registration must be rejected due to validation errors", ((string)(null)), table7, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Register user with username and email address greater than max lenght")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Register user with username and email address greater than max lenght")]
        [global::Xunit.TraitAttribute("Category", "UserRegistration")]
        public async global::System.Threading.Tasks.Task RegisterUserWithUsernameAndEmailAddressGreaterThanMaxLenght()
        {
            string[] tagsOfScenario = new string[] {
                    "UserRegistration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register user with username and email address greater than max lenght", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 58
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
 await testRunner.AndAsync("I have user registration data with \"values greater than max lenght\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
 await testRunner.WhenAsync("I register the user", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table8.AddRow(new string[] {
                            "The username cannot be greater than 50"});
                table8.AddRow(new string[] {
                            "The email address cannot be greater than 100"});
#line 62
 await testRunner.ThenAsync("the user registration must be rejected due to validation errors", ((string)(null)), table8, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Register user with invalid email address and password")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Register user with invalid email address and password")]
        [global::Xunit.TraitAttribute("Category", "UserRegistration")]
        public async global::System.Threading.Tasks.Task RegisterUserWithInvalidEmailAddressAndPassword()
        {
            string[] tagsOfScenario = new string[] {
                    "UserRegistration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register user with invalid email address and password", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 69
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 70
 await testRunner.AndAsync("I have user registration data with \"invalid email address and password\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
 await testRunner.WhenAsync("I register the user", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table9.AddRow(new string[] {
                            "The email address is invalid"});
                table9.AddRow(new string[] {
                            "The password is invalid"});
#line 72
 await testRunner.ThenAsync("the user registration must be rejected due to validation errors", ((string)(null)), table9, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Register user with a different password confirmation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Register user with a different password confirmation")]
        [global::Xunit.TraitAttribute("Category", "UserRegistration")]
        public async global::System.Threading.Tasks.Task RegisterUserWithADifferentPasswordConfirmation()
        {
            string[] tagsOfScenario = new string[] {
                    "UserRegistration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register user with a different password confirmation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 78
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 79
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 80
 await testRunner.AndAsync("I have user registration data with \"password different\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
 await testRunner.WhenAsync("I register the user", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table10.AddRow(new string[] {
                            "The password is different from the confirmation"});
#line 82
 await testRunner.ThenAsync("the user registration must be rejected due to validation errors", ((string)(null)), table10, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Register user with a profile name not found")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Register user with a profile name not found")]
        [global::Xunit.TraitAttribute("Category", "UserRegistration")]
        public async global::System.Threading.Tasks.Task RegisterUserWithAProfileNameNotFound()
        {
            string[] tagsOfScenario = new string[] {
                    "UserRegistration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Register user with a profile name not found", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 87
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 89
 await testRunner.AndAsync("I have user registration data with \"profile not found\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
 await testRunner.WhenAsync("I register the user", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table11.AddRow(new string[] {
                            "The user profile not found"});
#line 91
 await testRunner.ThenAsync("the user registration must be rejected due to validation errors", ((string)(null)), table11, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change the password of a user logged in with a manager profile")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change the password of a user logged in with a manager profile")]
        [global::Xunit.TraitAttribute("Category", "UserRegistration")]
        public async global::System.Threading.Tasks.Task ChangeThePasswordOfAUserLoggedInWithAManagerProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "UserRegistration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change the password of a user logged in with a manager profile", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 96
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 97
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 98
 await testRunner.AndAsync("I have password change data for my user with \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 100
 await testRunner.ThenAsync("the password must be changed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change the password of a user logged in with a customer profile")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change the password of a user logged in with a customer profile")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeThePasswordOfAUserLoggedInWithACustomerProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change the password of a user logged in with a customer profile", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 103
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
 await testRunner.GivenAsync("I am authenticated in with the \"customer profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
 await testRunner.AndAsync("I have password change data for my user with \"customer profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
 await testRunner.ThenAsync("the password must be changed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change another user\'s password while authenticated with the manager profile")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change another user\'s password while authenticated with the manager profile")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeAnotherUsersPasswordWhileAuthenticatedWithTheManagerProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change another user\'s password while authenticated with the manager profile", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 110
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 111
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 112
 await testRunner.AndAsync("I have password change data for another user with \"customer profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
 await testRunner.ThenAsync("the password must be changed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change another user\'s password while authenticated with the customer profile")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change another user\'s password while authenticated with the customer profile")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeAnotherUsersPasswordWhileAuthenticatedWithTheCustomerProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change another user\'s password while authenticated with the customer profile", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 117
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 118
 await testRunner.GivenAsync("I am authenticated in with the \"customer profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 119
 await testRunner.AndAsync("I have password change data for another user with \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 121
 await testRunner.ThenAsync("the password must not be changed due to insufficient permissions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change user password without being authenticated")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change user password without being authenticated")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeUserPasswordWithoutBeingAuthenticated()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change user password without being authenticated", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 124
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 125
 await testRunner.GivenAsync("I am not authenticated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 126
 await testRunner.AndAsync("I have password change data for user with \"valid values\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 128
 await testRunner.ThenAsync("the password change must be rejected because the user is not authenticated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change user password with invalid authenticated")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change user password with invalid authenticated")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeUserPasswordWithInvalidAuthenticated()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change user password with invalid authenticated", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 131
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 132
 await testRunner.GivenAsync("I am not authenticated due to invalid credentials", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 133
 await testRunner.AndAsync("I have password change data for user with \"valid values\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 135
 await testRunner.ThenAsync("the password change must be rejected because the user is not authenticated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change user password with default values")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change user password with default values")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeUserPasswordWithDefaultValues()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change user password with default values", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 138
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 139
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 140
 await testRunner.AndAsync("I have password change data for user with \"default values\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table12.AddRow(new string[] {
                            "The email address cannot be null or empty"});
                table12.AddRow(new string[] {
                            "The password cannot be null or empty"});
#line 142
 await testRunner.ThenAsync("the password must not be changed due to validation errors", ((string)(null)), table12, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change user password with null values")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change user password with null values")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeUserPasswordWithNullValues()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change user password with null values", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 148
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 149
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 150
 await testRunner.AndAsync("I have password change data for user with \"null values\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 151
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table13.AddRow(new string[] {
                            "The email address cannot be null or empty"});
                table13.AddRow(new string[] {
                            "The password cannot be null or empty"});
#line 152
 await testRunner.ThenAsync("the password must not be changed due to validation errors", ((string)(null)), table13, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change user password with email address greater than max lenght")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change user password with email address greater than max lenght")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeUserPasswordWithEmailAddressGreaterThanMaxLenght()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change user password with email address greater than max lenght", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 158
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 159
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 160
 await testRunner.AndAsync("I have password change data for user with \"email address greater than max lenght\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table14.AddRow(new string[] {
                            "The email address cannot be greater than 100"});
#line 162
 await testRunner.ThenAsync("the password must not be changed due to validation errors", ((string)(null)), table14, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change user password with invalid email address and password")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change user password with invalid email address and password")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeUserPasswordWithInvalidEmailAddressAndPassword()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change user password with invalid email address and password", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 167
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 168
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 169
 await testRunner.AndAsync("I have password change data for user with \"invalid email address and password\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 170
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table15.AddRow(new string[] {
                            "The email address is invalid"});
                table15.AddRow(new string[] {
                            "The password is invalid"});
#line 171
 await testRunner.ThenAsync("the password must not be changed due to validation errors", ((string)(null)), table15, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change user password with a different password confirmation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change user password with a different password confirmation")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeUserPasswordWithADifferentPasswordConfirmation()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change user password with a different password confirmation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 177
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 178
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 179
 await testRunner.AndAsync("I have password change data for user with \"password different\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 180
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table16.AddRow(new string[] {
                            "The password is different from the confirmation"});
#line 181
 await testRunner.ThenAsync("the password must not be changed due to validation errors", ((string)(null)), table16, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change user password with a user not found")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change user password with a user not found")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeUserPasswordWithAUserNotFound()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change user password with a user not found", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 186
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 187
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 188
 await testRunner.AndAsync("I have password change data for user with \"user not found\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 189
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table17.AddRow(new string[] {
                            "The email address or password is incorrect"});
#line 190
 await testRunner.ThenAsync("the password must not be changed due to validation errors", ((string)(null)), table17, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change user password with incorrect password")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User management")]
        [global::Xunit.TraitAttribute("Description", "Change user password with incorrect password")]
        [global::Xunit.TraitAttribute("Category", "UserPasswordChange")]
        public async global::System.Threading.Tasks.Task ChangeUserPasswordWithIncorrectPassword()
        {
            string[] tagsOfScenario = new string[] {
                    "UserPasswordChange"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change user password with incorrect password", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 195
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 196
 await testRunner.GivenAsync("I am authenticated in with the \"manager profile\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 197
 await testRunner.AndAsync("I have password change data for user with \"incorrect password\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 198
 await testRunner.WhenAsync("I change my password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table18.AddRow(new string[] {
                            "The email address or password is incorrect"});
#line 199
 await testRunner.ThenAsync("the password must not be changed due to validation errors", ((string)(null)), table18, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UserManagementFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UserManagementFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
